// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> mapTex;

float radius;
float2 mousePos;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    if ((mousePos.x - id.x) * (mousePos.x - id.x) + (mousePos.y - id.y) * (mousePos.y - id.y) < radius * radius)
        mapTex[id.xy] = 1.0;
}
